Equation
    EnergyMin(age,sex)        'Minimum energy intake by age group'
    ProteinMin(age,sex)       'Minimum protein intake by age group'
    CalciumMin(age,sex)       'Minimum calcium intake by age group'
    IronMin(age,sex)          'Minimum iron intake by age group'
    MagnesiumMin(age,sex)     'Minimum magnesium intake by age group'
    CopperMin(age,sex)        'Minimum copper intake by age group'
    PhosphorusMin(age,sex)    'Minimum phosphorus intake by age group'
    ZincMin(age,sex)          'Minimum zinc intake by age group'
    ThiaminMin(age,sex)       'Minimum thiamin intake by age group'
    NiacinMin(age,sex)        'Minimum niacin intake by age group'
    RiboflavinMin(age,sex)    'Minimum riboflavin intake by age group'
    FolateMin(age,sex)        'Minimum folate intake by age group'
    VitaminAMin(age,sex)      'Minimum vitamin A intake by age group'
    VitaminCMin(age,sex)      'Minimum vitamin C intake by age group'
    VitaminB6Min(age,sex)     'Minimum vitamin B6 intake by age group'
    PotassiumMin(age,sex)     'Minimum potassium intake by age group'
    LandUB              'Total land use'
    GHGUB               'Total GHG emissions'
    WaterUB             'Total water use'
    AcidUB              'Total Acidifying Emissions'
    EutrUB              'Total Eutrophying Emissions'
* modified for sex dimension: total food weight bounds sum over all age-sex groups
    WeightMax          'Upper bound on total food demand'
    WeightMin          'Lower bound on total food demand'
    dvar                'Definition of objective value'
;
